package by.grsu.by.datamodel;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

public class CarModels extends AbstractModel implements Serializable {
	private static List<String> carModels = Arrays.asList(new String[] { 
					"AC" , 
					"Acura" , 
					"Alfa Romeo" , 
					"Alpina" , 
					"Alpine" , 
					"Aro" , 
					"Asia" , 
					"Aston Martin" , 
					"Audi" , 
					"Austin" , 
					"BAW" , 
					"Beijing" , 
					"Bentley" , 
					"BMW" , 
					"Brilliance" , 
					"Bristol" , 
					"Bugatti" , 
					"Buick" , 
					"BYD" , 
					"¡Ó„‰‡Ì" , 
					"Vector" , 
					"Venturi" , 
					"Volkswagen" , 
					"Volvo" , 
					"Vortex" , 
					"Wartburg" , 
					"Westfield" , 
					"Wiesmann" , 
					"Wuling" , 
					"¬¿« (Lada)" , 
					"Geely" , 
					"Geo" , 
					"GMC" , 
					"Great Wall" , 
					"√¿«" , 
					"Dacia" , 
					"Dadi" , 
					"Daewoo" , 
					"Daihatsu" , 
					"Daimler" , 
					"Dallas" , 
					"Derways" , 
					"De Tomaso" , 
					"Dodge" , 
					"Dong Feng" , 
					"Doninvest" , 
					"Jeep" , 
					"Jiangling" , 
					"Jiangnan" , 
					"Eagle" , 
					"Zastava" , 
					"ZX" , 
					"«¿«" , 
					"«»À" , 
					"Infiniti" , 
					"Innocenti" , 
					"Invicta" , 
					"Iran Khodro" , 
					"Isdera" , 
					"Isuzu" , 
					"IVECO" , 
					"Xin Kai" , 
					"»∆" , 
					"Cadillac" , 
					"Callaway" , 
					"Carbodies" , 
					"Caterham" , 
					"Citroen" , 
					"Cizeta" , 
					"Coggiola" , 
					"Kia" , 
					"Koenigsegg" , 
					"Qvale" , 
					" ¿Ã¿«" , 
					"Lamborghini" , 
					"Lancia" , 
					"Land Rover" , 
					"Landwind" , 
					"Lexus" , 
					"Lifan" , 
					"Lincoln" , 
					"Lotus" , 
					"LTI" , 
					"Luxgen" , 
					"ÀÛ¿«" , 
					"Mahindra" , 
					"Marcos" , 
					"Marlin" , 
					"Marussia" , 
					"Maruti" , 
					"Maserati" , 
					"Maybach" , 
					"Mazda" , 
					"McLaren" , 
					"Mega" , 
					"Mercedes-Benz" , 
					"Mercury" , 
					"Metrocab" , 
					"MG" , 
					"Minelli" , 
					"Mini" , 
					"Mitsubishi" , 
					"Mitsuoka" , 
					"Monte Carlo" , 
					"Morgan" , 
					"ÃÓÒÍ‚Ë˜" ,  
					"Nissan" , 
					"Noble" , 
					"Oldsmobile" , 
					"Opel" , 
					"Pagani" , 
					"Panoz" , 
					"Paykan" , 
					"Perodua" , 
					"Peugeot" , 
					"Plymouth" , 
					"Pontiac" , 
					"Porsche" , 
					"Premier" , 
					"Proton" , 
					"Puma" ,  
					"Reliant" , 
					"Renault" , 
					"Rolls-Royce" , 
					"Ronart" , 
					"Rover" , 
					"Saab" , 
					"Saleen" , 
					"Samsung" , 
					"Saturn" , 
					"Scion" , 
					"SEAT" , 
					"Skoda" , 
					"SMA" , 
					"Smart" , 
					"Soueast" , 
					"Spectre" , 
					"SsangYong" , 
					"Subaru" , 
					"Suzuki" , 
					"—Â¿«" , 
					"Talbot" , 
					"Tata" , 
					"Tatra" , 
					"Tianma" , 
					"Tofas" , 
					"Toyota" , 
					"Trabant" , 
					"TVR" , 
					"“‡„¿«" , 
					"”¿«" , 
					"FAW" , 
					"Ferrari" , 
					"Fiat" , 
					"Ford" , 
					"FSO" , 
					"Fuqi" , 
					"Hafei",
					"Haima" , 
					"Hindustan" , 
					"Holden" , 
					"Honda" , 
					"HuangHai" , 
					"Hummer" , 
					"Hyundai" , 
					"Chana" , 
					"ChangFeng" , 
					"Changhe" , 
					"Chery" , 
					"Chevrolet" , 
					"Chrysler" , 
					"Shifeng" , 
					"ShuangHuan",
					"JAC", 
					"Jaguar" 
	});

	public static List<String> getCarModels() {
		return carModels;
	}

}
